const actionsTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_COUNT_CART_ITEM: "INCREMENT_COUNT_CART_ITEM",
  DECREMENT_COUNT_CART_ITEM: "DECREMENT_COUNT_CART_ITEM",
};

export { actionsTypes };
