const actionsTypes = {
  SHOW_CART_MODAL: "SHOW_CART_MODAL",
  CLOSE_CART_MODAL: "CLOSE_CART_MODAL",
  SHOW_SEARCH_MODAL: "SHOW_SEARCH_MODAL",
  CLOSE_SEARCH_MODAL: "CLOSE_SEARCH_MODAL",
  SHOW_IMG_MODAL: "SHOW_IMG_MODAL",
  CLOSE_IMG_MODAL: "CLOSE_IMG_MODAL",
};

export { actionsTypes };
